/// THIS FILE WAS GENERATED BY CLAUDE AI. THIS IS ONLY USED FOR THE PURPOSES OF FINDING PIDF CONSTANTS; IT WILL NOT BE RUN IN COMPETITION.

package org.firstinspires.ftc.teamcode;

import com.acmerobotics.dashboard.FtcDashboard;
import com.acmerobotics.dashboard.config.Config;
import com.acmerobotics.dashboard.telemetry.MultipleTelemetry;
import com.arcrobotics.ftclib.controller.PIDController;
import com.qualcomm.robotcore.eventloop.opmode.OpMode;
import com.qualcomm.robotcore.eventloop.opmode.TeleOp;
import com.qualcomm.robotcore.hardware.DcMotor;
import com.qualcomm.robotcore.hardware.DcMotorEx;

@Config
@TeleOp(name="PIDF Tuner", group="Tuning")
public class PIDFTuner extends OpMode {
    private PIDController controller;

    // Start with VERY conservative values
    public static double p = 0.2, i = 0, d = 0;
    public static double f = 0;

    // Toggle between manual PID and simple power test
    public static boolean usePID = false;
    public static double testPower = 0.3;  // For basic power testing

    static final float COUNTS_PER_FULL_REV = 96.245f;

    private DcMotorEx magazine;
    private int target = 0;
    private boolean buttonPressed = false;

    @Override
    public void init() {
        controller = new PIDController(p, i, d);
        telemetry = new MultipleTelemetry(telemetry, FtcDashboard.getInstance().getTelemetry());

        magazine = hardwareMap.get(DcMotorEx.class, "magazine");
        magazine.setDirection(DcMotor.Direction.FORWARD);
        magazine.setMode(DcMotor.RunMode.STOP_AND_RESET_ENCODER);
        magazine.setMode(DcMotor.RunMode.RUN_WITHOUT_ENCODER);
        magazine.setZeroPowerBehavior(DcMotor.ZeroPowerBehavior.BRAKE);

        telemetry.addLine("INIT COMPLETE");
        telemetry.addLine("Press A button to rotate 1 full revolution");
        telemetry.addLine("Set usePID=false to test with simple power");
        telemetry.addLine("Set usePID=true to test PID control");
        telemetry.update();
    }

    @Override
    public void loop() {
        // Press A button to add one full rotation to target
        if (gamepad1.a && !buttonPressed) {
            target += (int) COUNTS_PER_FULL_REV;
            buttonPressed = true;
        }
        if (!gamepad1.a) {
            buttonPressed = false;
        }

        int currentPos = magazine.getCurrentPosition();
        double power = 0;

        if (!usePID) {
            // Simple power test - just apply constant power
            if (currentPos < target) {
                power = testPower;
            } else {
                power = 0;
            }

            telemetry.addLine("=== SIMPLE POWER MODE ===");
            telemetry.addData("Test Power", testPower);
        } else {
            // PID control mode
            controller.setPID(p, i, d);
            double pid = controller.calculate(currentPos, target);

            // Simplified feedforward - only if you need it
            double ff = f;

            power = pid + ff;
            power = Math.max(-1.0, Math.min(1.0, power));

            telemetry.addLine("=== PID CONTROL MODE ===");
            telemetry.addData("PID Output", pid);
            telemetry.addData("Feedforward", ff);
            telemetry.addData("P", p);
            telemetry.addData("I", i);
            telemetry.addData("D", d);
            telemetry.addData("F", f);
        }

        magazine.setPower(power);

        telemetry.addLine("Press A to add 1 rotation");
        telemetry.addData("Current Position", currentPos);
        telemetry.addData("Target Position", target);
        telemetry.addData("Error", target - currentPos);
        telemetry.addData("Power Applied", power);
        telemetry.addData("Mode", usePID ? "PID" : "Simple Power");
        telemetry.update();
    }
}